title: Wenchen (Neo) Li
description: "Front-End Engineer Crafting Marketing Websites"
show_downloads: false
theme: jekyll-theme-leap-day
google_analytics: UA-58523664-7
markdown: GFM
sass:
  sass_dir: assets/css
